### PR TITLE
Unlisten before calling listener and bind to target by default

### LINKED ISSUE #4919: Layer on change event issue when migrating from 3.10.1 to 3.14.0
I was using the following code to access features on a layer once they are loaded. It no longer works, and I get the following error: `Uncaught TypeError: Cannot read property 'getSource' of undefined`. Here is the code that worked under 3.10.1:

    // Wait until all features are loaded, then process features
    myLayer.once( "change", function ( evt ) {
        this.getSource().forEachFeature( function ( feature ) {
            // set feature id's etc...
        })
    })

`this` is undefined. Is there another/better way to do this now?

### PR DESCRIPTION
**Pull request by ahocevar**
The problem reported in #4919 is a regression caused by the `goog.events.*` removal. Listeners were always called synchronously, but the difference with the new implementation is that a `once` listener is unregistered *after* calling the listener, whereas it was unregistered *before* previously. The second problem is that when `opt_this` is not provided, we no longer bind to the event target by default.

Fixes #4919.

### CODE REVIEW

File: examples/vector-layer.js [hunk 1]
```diff
@@ -41,6 +41,12 @@ var vectorLayer = new ol.layer.Vector({
     return style;
   }
 });
+var id = 0;
+vectorLayer.once('change', function() {
+  this.getSource().forEachFeature(function(feature) {
+    feature.setId(id++);
+  });
+});
```
Comment (tschaub) [inline examples/vector-layer.js]: Was this meant to be a test instead? :)

Comment (ahocevar) [inline examples/vector-layer.js]: Yes, I'll be pushing an update shortly.

**Comment by ahocevar** [comment]
Tests added.

**Comment by tschaub** [comment]
Nice fix @ahocevar.  Please merge.

**Comment by ahocevar** [comment]
Thanks for the quick review @tschaub.
