### PR TITLE
Scale StaticImage image to imageExtent

### LINKED ISSUE #2844: Incorrect rendered Extent of ImageStatic
If I add an ImageStatic to a Map, its rendered too wide (in horizontal direction). Its maxx (right extent) appears at the false position.

Example: http://jsfiddle.net/u7xyor0t/1/

The Image is intended to reach from 8° to 9° East. But its right border appears at about 9.5° E... (you can check this with the Mouse Position)

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/5296274-incorrect-rendered-extent-of-imagestatic?utm_campaign=plugin&utm_content=tracker%2F79013&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F79013&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ahocevar**
The imageSize property was only used to determine the scale. It's usage was never documented nor tested nor shown in an example, so I removed it because I considered its presence a bug.

Fixes #2844.

### CODE REVIEW

File: src/ol/source/imagestaticsource.js [hunk 1]
```diff
@@ -42,16 +37,34 @@ ol.source.ImageStatic = function(options) {
...
-  this.image_ = new ol.Image(imageExtent, resolution, 1, attributions,
+  this.image_ = new ol.Image(imageExtent, undefined, 1, attributions,
       options.url, crossOrigin, imageLoadFunction);
+
+  goog.events.listen(this.image_, goog.events.EventType.CHANGE, function() {
+    if (this.image_.getState() == ol.ImageState.LOADED) {
+      var image = this.image_.getImage();
+      var resolution = ol.extent.getHeight(imageExtent) / image.height;
+      var pxWidth = Math.ceil(ol.extent.getWidth(imageExtent) / resolution);
+      var pxHeight = Math.ceil(ol.extent.getHeight(imageExtent) / resolution);
```
Comment (bartvde) [inline src/ol/source/imagestaticsource.js]: minor but we're calling ```ol.extent.getHeight(imageExtent)``` twice here

**Comment by bartvde** [comment]
Nice way to handle this @ahocevar much better.
LGTM.

File: src/ol/source/imagestaticsource.js [hunk 2]
```diff
@@ -42,16 +37,34 @@ ol.source.ImageStatic = function(options) {
...
 
   /**
    * @private
    * @type {ol.Image}
    */
-  this.image_ = new ol.Image(imageExtent, resolution, 1, attributions,
+  this.image_ = new ol.Image(imageExtent, undefined, 1, attributions,
       options.url, crossOrigin, imageLoadFunction);
+
+  goog.events.listen(this.image_, goog.events.EventType.CHANGE, function() {
```
Comment (tschaub) [inline src/ol/source/imagestaticsource.js]: There are now two listeners for `CHANGE`.  Is it important that this listener get called first?

What would you think about registering a single listener (`this.handleImageChange_`) and having that call the parent method (`this.handleImageChange`)?

File: externs/olx.js [hunk 3]
```diff
@@ -4975,14 +4974,6 @@ olx.source.ImageStaticOptions.prototype.imageExtent;
 
 
 /**
- * Size of the image in pixels.
- * @type {ol.Size|undefined}
- * @api stable
- */
-olx.source.ImageStaticOptions.prototype.imageSize;
```
Comment (tschaub) [inline externs/olx.js]: Not sure if anybody was using it this way, but if anybody is using an SVG as an image source, the size needs to be set explicitly in IE.  Edge case perhaps, but it would be good to at least document in the upgrade notes that the image size can no longer be set.

Comment (ahocevar) [inline externs/olx.js]: Ok, I'll create a follow up pull request on Monday.

File: src/ol/source/imagestaticsource.js (hunk 2 above)
Comment (ahocevar) [inline src/ol/source/imagestaticsource.js]: Yes, it is important that this one has s called first.

File: externs/olx.js (hunk 3 above)
Comment (ahocevar) [inline externs/olx.js]: Looks like it makes sense then to bring the imageSize property back. Will incorporate all of @tschaub's suggestions in the follow up pull request.

Comment (tschaub) [inline externs/olx.js]: @ahocevar your change looks like a definite improvement.  We should clarify exactly where the size property is needed.  I'm only guessing about the SVG/IE case because of a recent experience with an icon symbolizer.

**Comment by ahocevar** [comment]
See #4426 for the follow-up pull request which addresses comments by @tschaub and @bartvde.
