### PR TITLE
Make pixel projection handling work in compiled mode

### LINKED ISSUE #4676: Vector tiles rendering broken in compiled build when pixel units are used
See http://openlayers.org/en/master/examples/mapbox-vector-tiles.html.

### PR DESCRIPTION
**Pull request by ahocevar**
The compiler seems to have trouble with functions that can run with
different 'this' types. By moving the units handling to the callback, this
issue can be avoided.

Fixes #4676.

### CODE REVIEW

File: src/ol/featureloader.js [hunk 1]
```diff
@@ -174,9 +174,10 @@ ol.featureloader.xhr = function(url, format) {
   return ol.featureloader.loadFeaturesXhr(url, format,
       /**
        * @param {Array.<ol.Feature>} features The loaded features.
+       * @param {ol.proj.Projection} dataProjectin Data projection.
```
Comment (tschaub) [inline src/ol/featureloader.js]: Should be `dataProjection`.  I've just confirmed that the `valid-jsdoc` rule catches this for a function declaration.  I'll dig a bit more to see why it isn't caught here.

Comment (tschaub) [inline src/ol/featureloader.js]: See eslint/eslint#4964 for the upstream issue.

**Comment by tschaub** [comment]
This change looks good to me @ahocevar.  I didn't test manually, but assuming our tests cover it, this looks good to merge.
