### PR TITLE
WMTS Get Cap document with updated WMTS.optionsFromCapabilities function 

### LINKED ISSUE #2721: WMTSCapabilities in 3.0 final
The example http://openlayers.org/en/v3.0.0-beta.1/examples/wmts-from-capabilities.html doesn't work for me in 3.0-final. Obviously, ol.parser.ogc.WMTSCapabilities is missing as like the other classes in namespace ol.parser.* are. Will they be here again in upcoming releases? 

Thanks!

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/4422794-wmtscapabilities-in-3-0-final?utm_campaign=plugin&utm_content=tracker%2F79013&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F79013&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sarametz**
Building on pull request #3026 which fixes #2721, I altered the ol.source.WMTS.optionsFromCapabilities and ol.tilegrid.WMTS.createFromCapabilitiesMatrixSet functions to use the updated variable names (changed to be consistent with the WMS GetCapabilities format). This allows for WMTS sources to be easily created from a capabilities document. I have added a few tests for these and an example.

I have also altered the REST url template replacement to be case insensitive as some WMTS services use  {Style} and some use {style}. The WMTS spec seems to use the two interchangeably.

### CODE REVIEW

**Comment by elemoine** [comment]
https://github.com/openlayers/ol3/pull/3026 is closed. This PR needs rebasing.

**Comment by sarametz** [comment]
@elemoine I've rebased this PR, is there anything else I need to do before review?

File: examples/wmts-layer-from-capabilities.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+  var options = ol.source.WMTS.optionsFromCapabilities(result,
+      { layer: 'dem:oceanbottom', matrixSet: 'EPSG:3857'});
+
+  var projection = ol.proj.get('EPSG:3857');
+  var projectionExtent = projection.getExtent();
+  map = new ol.Map({
+    layers: [
+      new ol.layer.Tile({
+        opacity: 1,
+        extent: projectionExtent,
```
Comment (probins) [inline examples/wmts-layer-from-capabilities.js]: shouldn't the layer extent be taken from the BoundingBox in the capabilities doc if present?

File: examples/wmts-layer-from-capabilities.js [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+goog.require('ol.proj');
+goog.require('ol.source.WMTS');
+
+var parser = new ol.format.WMTSCapabilities();
+var map;
+
+$.ajax('data/WMTSCapabilities.xml').then(function(response) {
+  var result = parser.read(response);
+  var options = ol.source.WMTS.optionsFromCapabilities(result,
+      { layer: 'dem:oceanbottom', matrixSet: 'EPSG:3857'});
```
Comment (elemoine) [inline examples/wmts-layer-from-capabilities.js]: Minor, but please remove the space before `layer` here.

**Comment by elemoine** [comment]
@sarametz, this looks great! Do we have a CLA from you already?

**Comment by sarametz** [comment]
@probins using the bounding box from the capabilities document in that situation would require another function to create a tile layer from a capabilities document. So far in this PR I have just modified existing functions that were not currently working. @elemoine do you think it would be worth adding such a function? Also, I have removed the space.

**Comment by sarametz** [comment]
@elemoine Koordinates Ltd. has submitted a CLA which I am included in

**Comment by elemoine** [comment]
I just tested the example and I got an empty map. It looks like the WMTS you rely on in the example is down.

**Comment by sarametz** [comment]
@elemoine I have updated the example to use a different WMTS layer, this involved replacing the capabilities document at examples/data/WMTSCapabilities.xml, which is only seems to be used in the example in #3026 which just parses the document

**Comment by elemoine** [comment]
Thank you. I'll look at it once more and merge.

File: src/ol/source/wmtssource.js [hunk 3]
```diff
@@ -239,90 +241,144 @@ ol.source.WMTS.prototype.updateDimensions = function(dimensions) {
...
+  } else {
+    projection = ol.proj.get(matrixSetObj['SupportedCRS'].replace(
+        /urn:ogc:def:crs:(\w+):(.*:)?(\w+)$/, '$1:$3'));
+  }
+
+  /** @type {!Array.<string>} */
+  var urls = [];
+  var requestEncoding = config['requestEncoding'];
+  if (wmtsCap['OperationsMetadata'].hasOwnProperty('GetTile') &&
+      requestEncoding != 'REST') {
```
Comment (elemoine) [inline src/ol/source/wmtssource.js]: We used to support both `REST` and `RESTful` as the request encoding string? Any reason for removing `RESTful`? I think it was there for a good reason.

**Comment by elemoine** [comment]
I just added a last comment regarding `RESTful` as the request encoding string. But, I'm going to merge this PR now anyway, as I am sure you will come with a new PR if my comment makes sense :)

Thanks a lot for your good patches @sarametz!

File: src/ol/source/wmtssource.js (hunk 3 above)
Comment (sarametz) [inline src/ol/source/wmtssource.js]: @elemoine I didn't realise I had removed it, #3295 should add it back in
