### PR TITLE
Measure tooltips touchdevice

### LINKED ISSUE #3370: Measure example not working well on mobile
The tooltip "Click tho start drawing" does not appear on the screen and when you zoom out it appears, but not at the good place.

Also, when you click on the screen, the measurement is not displayed.

Tested with a Nexus 5 via the following url:
http://openlayers.org/en/v3.3.0/examples/measure.html

### PR DESCRIPTION
**Pull request by pgiraud**
This pull requests makes it so the measure are displayed on touch devices as well. The measurement is displayed when the drawn geometry changes ie. when a new point is added on touch devices.

Also, the help tooltip is hidden when the cursor moves out of the map which prevents it from being displayed in a weird place sometimes.

Fixes #3370.
There's still a problem when user taps the zoomout button on a touch device.

Please review.

### CODE REVIEW

File: examples/measure.js [hunk 1]
```diff
@@ -138,6 +132,10 @@ var map = new ol.Map({
 
 map.on('pointermove', pointerMoveHandler);
 
+map.on('mouseout', function() {
```
Comment (tschaub) [inline examples/measure.js]: Did you mean to use `jQuery.mouseleave()` here?  The map doesn't fire a `mouseout` event.

Comment (pgiraud) [inline examples/measure.js]: Indeed. I wanted to observe `mouseout` on `$(map.getViewport())` actually.
Good catch.

**Comment by fredj** [comment]
LGTM
