### PR TITLE
Remove use of goog.uri

### LINKED ISSUE #5430: WMS param STYLES is by default sent without =
This is a regression in 3.16.0. 

Problem can be seen in the example:
http://openlayers.org/en/v3.16.0/examples/wms-image.html?q=wms

WMS request like the following can be observed:
`http://demo.boundlessgeo.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=topp%3Astates&CRS=EPSG%3A3857&STYLES&WIDTH=986&HEIGHT=532&BBOX=-15492472.25%2C2003371.5%2C-5847584.75%2C7205188.5`

Issue existed before and was fixed #242 (pre 3.0) but probably had another cause back then.

### PR DESCRIPTION
**Pull request by bjornharrtell**
Resolves #5430.

### CODE REVIEW

File: src/ol/source/imagewmssource.js [hunk 1]
```diff
@@ -312,7 +312,7 @@ ol.source.ImageWMS.prototype.getRequestUrl_ = function(extent, size, pixelRatio,
   }
   params['BBOX'] = bbox.join(',');
 
-  return goog.uri.utils.appendParamsFromMap(this.url_, params);
+  return this.url_ + '?' + ol.ext.querystring.stringify(params);
```
Comment (bartvde) [inline src/ol/source/imagewmssource.js]: what if people pass in a & or ? already in the url?

Comment (bjornharrtell) [inline src/ol/source/imagewmssource.js]: Mmm yes, good point. Perhaps it would be better to incorporate goog.uri.utils.appendParamsFromMap into ol with the quirk for empty strings removed?

Comment (bjornharrtell) [inline src/ol/source/imagewmssource.js]: goog.uri.utils.appendParamsFromMap is pretty hairy... I will see if I can find any suitable replacement.

Comment (bjornharrtell) [inline src/ol/source/imagewmssource.js]: No luck. :( Tried out using a full URI parser (https://github.com/petkaantonov/urlparser) but on second thought it seems too heavy.

Comment (probins) [inline src/ol/source/imagewmssource.js]: can you not just do `(url.indexOf('?') == -1) ? '?' : '&'` or similar?

**Comment by probins** [comment]
why introduce query-string here? Converting a params object to a `&key=value` string is surely not that complicated.
```
var qs = [];
for (var p in params) {
  if (params.hasOwnProperty(p)) {
    qs.push(p + "=" + encodeURIComponent(params[p]));
  }
}
return this.url_ + qs.join("&");
```
or similar

**Comment by bjornharrtell** [comment]
Agreed, I'll try to make a replacement for `appendParamsFromMap` without external dependencies.

**Comment by bjornharrtell** [comment]
Reimplemented based on suggestions from @probins and @bartvde, thanks!

File: src/ol/uri.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
+goog.provide('ol.uri');
+
+
+/**
+ * Appends query parameters from a map to an URI.
```
Comment (tschaub) [inline src/ol/uri.js]: I would avoid the use of the term "map" here.  In the case of our library, this is too easily confused with an instance of `ol.Map`.  In terms of the language, this is too easily confused with an instance of `Map`.  Instead, this could read:

> Appends query parameters to a URL.

File: src/ol/uri.js [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+ *
+ * @param {string} uri The original URI, which may already have query data.
```
Comment (tschaub) [inline src/ol/uri.js]: Do our uses of this always expect params to be appended rather than merged?

File: src/ol/uri.js [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+ * @param {!Object} map An object where keys are URI-encoded parameter keys,
+ *     and the values are arbitrary types or arrays.
+ * @return {string} The new URI.
+ */
+ol.uri.appendParamsFromMap = function(uri, map) {
```
Comment (tschaub) [inline src/ol/uri.js]: I'd be tempted to just call this `ol.uri.appendParams(uri, params)`.

File: src/ol/uri.js [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+  var qs = Object.keys(map).map(function(k) {
+    return k + '=' + encodeURIComponent(map[k]);
```
Comment (tschaub) [inline src/ol/uri.js]: Don't we also want to `encodURIComponent(k)` here?

**Comment by tschaub** [comment]
Thanks for the work on this @bjornharrtell.  It should be straightforward to write tests for this.

File: src/ol/uri.js (hunk 3 above)
Comment (bjornharrtell) [inline src/ol/uri.js]: From what I can tell the original `goog.uri.utils.appendParamsFromMap` only does append no merge.

**Comment by bjornharrtell** [comment]
Thanks @tschaub for additional input. Makes sense so I've made adjustments accordingly and have added two test cases.

File: src/ol/uri.js [hunk 6]
```diff
@@ -0,0 +1,17 @@
+goog.provide('ol.uri');
+
+
+/**
+ * Appends query parameters to a URI.
+ *
+ * @param {string} uri The original URI, which may already have query data.
+ * @param {!Object} params An object where keys are URI-encoded parameter keys,
```
Comment (marcjansen) [inline src/ol/uri.js]: After the recent changes, this doc should be changed, right?

File: src/ol/uri.js [hunk 7]
```diff
@@ -0,0 +1,17 @@
...
+ *     and the values are arbitrary types or arrays.
+ * @return {string} The new URI.
+ */
+ol.uri.appendParams = function(uri, params) {
+  var qs = Object.keys(params).map(function(k) {
+    return encodeURIComponent(k) + '=' + encodeURIComponent(params[k]);
+  });
+  return uri + (uri.indexOf('?') === -1 ? '?' : '&') + qs.join('&');
```
Comment (probins) [inline src/ol/uri.js]: I think this should be a bit more flexible to allow for people including '?' in the uri, as there may already be one or more parameters in uri. If uri ends with '?' or '&' just add the params without any prefix.

Comment (tschaub) [inline src/ol/uri.js]: I think you'll have to leave examples about what you think should be supported to make it clearer.  These can then be added to the tests below.

Comment (probins) [inline src/ol/uri.js]: for example, http://www.icc.cat/eng/Home-ICC/Digital-geoinformation/Online-services-Geoservices/Quick-WMS-WMTS-of-raster-cartography includes the '?' in the base url. http://www.ign.es/wms-inspire/mapa-raster?request=GetCapabilities&service=WMS has a parameter in the base url and finishes with '&'. I've found this sort of thing to be quite common with WMS. Of course, you could get around this by specifying in the docs that any trailing '?' or '&' should be left out, but ISTM better if the library can handle this. Having said that, it's probably also the case that browsers are clever enough to ignore duplicates like this.

Comment (probins) [inline src/ol/uri.js]: just tried some tests on these examples. In neither case does it seem to matter if there is a duplicate '??' or '&&'. However, the current `goog.uri` function removes any duplicates and if there are browsers/servers where this would create an error, it would be a regression if this new function doesn't do this. It should be pretty easy to remove the duplicate by not adding the '?' or '&' if `uri.slice(-1)` is '?' or '&' (or alternatively `uri = uri.slice(0,-1)`) or whatever.

Comment (marcjansen) [inline src/ol/uri.js]: In my experiemce the double questionmark in URLs is an error

Comment (ahocevar) [inline src/ol/uri.js]: To bring this to an end: @bjornharrtell, can you please change the line to
```js
return uri.replace(/\?&?/, '') + (uri.indexOf('?') === -1 ? '?' : '&') + qs.join('&');
```
Thanks.

Comment (probins) [inline src/ol/uri.js]: yup, that should also do it. I'd agree with @tschaub that it would be good to have tests for these cases

Comment (tschaub) [inline src/ol/uri.js]: Or just:
```js
uri.replace(/[?&]$/, '')
```

And test cases should be added for these:

```
http://example.com/foo
http://example.com/foo?
http://example.com/foo?bar=bam
http://example.com/foo?bar=bam&
http://example.com/foo?bar=bam&baz=bat
http://example.com/foo?bar=bam&baz=bat&bop=
// etc
```

**Comment by bjornharrtell** [comment]
Thanks for the thorough review and regexp expertise. I hope to be able to rework this PR shortly, as in today or next few days at most.

**Comment by probins** [comment]
it might also be a good idea to have a test for WMS that checks that `STYLES=` is output - which is what started this whole discussion :-) Could go in a separate PR though.

**Comment by bjornharrtell** [comment]
I'm a bit a loss on the intent of the regexp. The following:

```js
var uri = 'http://example.com/foo?'
uri.replace(/[?&]$/, '') + (uri.indexOf('?') === -1 ? '?' : '&')
```

Results in `http://example.com/foo&` which doesn't seem right.

**Comment by bjornharrtell** [comment]
Trying out `goog.uri.utils.appendParamsFromMap` it does not seem to handle duplicate ?? or &&. @probins you claimed otherwise?

I've tried this out in this fiddle: https://jsfiddle.net/s4sp7ne8/.

**Comment by bjornharrtell** [comment]
Implemented handling URLs ending with ? or & using `uri.slice(-1)` as suggested by @probins and added additional test cases.

**Comment by probins** [comment]
> Trying out goog.uri.utils.appendParamsFromMap it does not seem to handle duplicate ?? or &&. @probins you claimed otherwise?

what I meant was that if you define '?' or '&' in the uri string (which I'm currently doing to use the 2 example WMS servers I mentioned), it correctly does not append a second '?' or '&'.

**Comment by probins** [comment]
> Results in http://example.com/foo& which doesn't seem right.

yeah, because the 2nd part isn't operating on the 1st part. :-) Something like this should work:
```
var uri = 'http://example.com/foo?';
uri = uri.replace(/[?&]$/, '');
uri = uri + (uri.indexOf('?') === -1 ? '?' : '&');
```

**Comment by probins** [comment]
> var uri = 'http://example.com/foo?';
> uri = uri.replace(/[?&]$/, '');

or combine these 2 lines:
`var uri = 'http://example.com/foo?'.replace(/[?&]$/, '');`

**Comment by sweco-sebhar** [comment]
Thanks @probins, now I get it. :)

Note that I reverted the URL encoding of keys, since `goog.uri.utils.appendParamsFromMap` does not.

**Comment by bjornharrtell** [comment]
Thanks @probins, now I get it. :)

Note that I reverted the URL encoding of keys, since goog.uri.utils.appendParamsFromMap does not.

File: src/ol/uri.js (hunk 6 above)
Comment (bjornharrtell) [inline src/ol/uri.js]: Changed back into leaving keys untouched as this is the existing behaviour with `goog.uri.utils.appendParamsFromMap`.

File: src/ol/uri.js [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+ * @param {string} uri The original URI, which may already have query data.
+ * @param {!Object} params An object where keys are URI-encoded parameter keys,
+ *     and the values are arbitrary types or arrays.
+ * @return {string} The new URI.
+ */
+ol.uri.appendParams = function(uri, params) {
+  var qs = Object.keys(params).map(function(k) {
+    return k + '=' + encodeURIComponent(params[k]);
+  }).join('&');
+  // remove extraneous ? or &
```
Comment (probins) [inline src/ol/uri.js]: I think I'd change this to 'remove any trailing ? or &'

File: src/ol/uri.js [hunk 9]
```diff
@@ -0,0 +1,21 @@
...
+  uri = uri.replace(/[?&]$/, '')
+  // append ? or & if uri has existing parameters
```
Comment (probins) [inline src/ol/uri.js]: I think this would be better replacing 'if' by 'depending on whether'

**Comment by probins** [comment]
a couple of small comments on comments, but otherwise this LGTM. Thanks.

**Comment by sweco-sebhar** [comment]
Amended comments and squashed. Thanks to all involved for the great review work.

**Comment by bjornharrtell** [comment]
Amended comments and squashed. Thanks to all involved for the great review work.

**Comment by ahocevar** [comment]
Thanks for this effort @bjornharrtell. I'm merging this now despite missing semicolons at the end of two lines, but I'll create a follow-up pull request with updated eslint rules so we can enforce those.

**Comment by tschaub** [comment]
> Note that I reverted the URL encoding of keys, since goog.uri.utils.appendParamsFromMap does not.

I think we should encode keys and values.  Not sure what the justification is for not encoding keys (except that `goog` doesn't).

**Comment by bjornharrtell** [comment]
I made the assumption that encoding keys could potentially cause regressions.
