### PR TITLE
Fix HiDPI support for ArcGIS REST

### LINKED ISSUE #3311: retina issue on ArcGISREST sources
b_r30hfwsaezszf png-large

Created a new ticket from the latest comments here: https://github.com/openlayers/ol3/pull/3263#issuecomment-77236815

I'm seeing the same thing on my iPad

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #3311.

### CODE REVIEW

**Comment by ahocevar** [comment]
@bartvde Should I merge this? Also, does this warrant a bugfix release?

**Comment by bartvde** [comment]
I haven't tested it on my iPad but I trust the param change is good.

So please merge.

As it's a new component I think it's fine not to do a bugfix release?

**Comment by ahocevar** [comment]
Cool. I'll merge into master then. Thanks!

**Comment by cwgrant** [comment]
Thanks for addressing this!

File: src/ol/source/tilearcgisrestsource.js [hunk 1]
```diff
@@ -109,6 +109,7 @@ ol.source.TileArcGISRest.prototype.getRequestUrl_ =
   params['BBOX'] = tileExtent.join(',');
   params['BBOXSR'] = srid;
   params['IMAGESR'] = srid;
+  params['DPI'] = 90 * pixelRatio;
```
Comment (bartvde) [inline src/ol/source/tilearcgisrestsource.js]: hey @ahocevar one question on the value, is 90 used because of the OGC SLD value of 90.71?
I see the default if not specified is 96 on ArcGIS REST http://sampleserver1.arcgisonline.com/ArcGIS/SDK/REST/export.html

Comment (ahocevar) [inline src/ol/source/tilearcgisrestsource.js]: It is to make it consistent with WMS, where we also use 90 dpi.

Comment (bartvde) [inline src/ol/source/tilearcgisrestsource.js]: Ah seeing it now. Should this be a const somewhere instead?

Comment (ahocevar) [inline src/ol/source/tilearcgisrestsource.js]: I have no strong opinion on it.
